### ISSUE TITLE
zoom drag on mouseDown?

### ISSUE THREAD

**Issue by kobsTheReal** [AdamRisberg/react-input-position#1]
I'd like to implement a zoom feature but with the mouseDown. 
Any idea on how to achieve it?

**Comment by AdamRisberg** [comment]
This was a bug. Item position tracking while using the mouseDown activation method was supposed to work the same as it's touch counterpart, but the item position was never being updated. I just posted the fix (version 1.2.1).

**Comment by kobsTheReal** [comment]
Many thanks!
